create table app_user(id bigint primary key, todo_count integer not null);
create table todo(id bigint generated by default as identity primary key, user_id bigint not null, title varchar(255) not null);
